### ISSUE TITLE
Uncaught Error: Call to a member function get_result() on null

### ISSUE THREAD

**Issue by AmazingDreams** [wp-pay-extensions/contact-form-7#10]
An error occurs on a contact form with the mail extension enabled (full stacktrace below). The error occurs when simply loading the page with the form, and nothing has been POSTed yet.

On https://github.com/pronamic/wp-pronamic-pay-contact-form-7/blob/main/src/Extension.php#L241 it appears the `WPCF7_Submission::get_instance()` result is `null`...

I do not know Contact Form 7, but it seems this callback isn't supposed to be run yet - as there's nothing in POST data, WPCF7_Submission is supposed to be null.

The stacktrace:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_result() on null in /home/.../public_html/staging/wp-content/plugins/pronamic-pay-with-mollie-for-contact-form-7/packages/wp-pay-extensions/contact-form-7/src/Extension.php:241
Stack trace:
#0 /home/.../public_html/staging/wp-includes/class-wp-hook.php(308): Pronamic\WordPress\Pay\Extensions\ContactForm7\Extension->replace_mail_tags()
#1 /home/.../public_html/staging/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /home/.../public_html/staging/wp-content/plugins/contact-form-7/includes/mail.php(519): apply_filters()
#3 [internal function]: WPCF7_MailTaggedText->replace_tags_callback()
#4 /home/.../public_html/staging/wp-content/plugins/contact-form-7/includes/mail.php(451): preg_replace_callback()
#5 /home/.../public_html/staging/wp-content/plugins/contact-form-7/includes/mail.php(346): WPCF7_MailTaggedText->replace_tags()
#6 /home/.../public_html/staging/wp-content/plugins/send-pdf-for-contact-form-7/classes/send-pdf.php(421): wpcf7_mail_replace_tags()
#7 /home/.../public_html/staging/wp-content/plugins/send-pdf-for-contact-form-7/classes/send-pdf.php(2083): cf7_sendpdf->wpcf7pdf_name_pdf()
#8 /home/.../public_html/staging/wp-includes/class-wp-hook.php(308): cf7_sendpdf->wpcf7_add_footer()
#9 /home/.../public_html/staging/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#10 /home/.../public_html/staging/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/.../public_html/staging/wp-includes/general-template.php(3065): do_action()
#12 /home/.../public_html/staging/wp-content/themes/sydney/footer.php(42): wp_footer()
#13 /home/.../public_html/staging/wp-includes/template.php(783): require_once('/home/.../...')
#14 /home/.../public_html/staging/wp-includes/template.php(718): load_template()
#15 /home/.../public_html/staging/wp-includes/general-template.php(92): locate_template()
#16 /home/.../public_html/staging/wp-content/themes/sydney/page.php(45): get_footer()
#17 /home/.../public_html/staging/wp-includes/template-loader.php(106): include('/home/.../...')
#18 /home/.../public_html/staging/wp-blog-header.php(19): require_once('/home/.../...')
#19 /home/.../public_html/staging/index.php(17): require('/home/.../...')
#20 {main}
  thrown in /home/.../public_html/staging/wp-content/plugins/pronamic-pay-with-mollie-for-contact-form-7/packages/wp-pay-extensions/contact-form-7/src/Extension.php on line 241
```

**Comment by remcotolsma** [comment]
Thank you for reporting, the submission instance can indeed be `null`, we do not catch this sufficiently.

https://github.com/rocklobster-in/contact-form-7/blob/2cfaa472fa485c6d3366fcdd80701fdaf7f9e425/includes/submission.php#L28-L47

PR https://github.com/pronamic/wp-pronamic-pay-contact-form-7/pull/11 is open, waiting for review from my colleague @rvdsteege.
